# -*- coding: utf-8 -*-
"""Decodelabs-Task-03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x89EoBPepOaKrVo-r-RurI_I1uHQxCx5

Um Ul Baneen
Artificial Intelligence Internship
"""

"""
Random Password Generator
Asks the user for a desired length and generates a random password
using letters, numbers, and symbols.
"""

import random
import string


def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = "".join(random.choice(characters) for _ in range(length))
    return password


def main():
    print("Random Password Generator")

    while True:
        user_input = input("Enter desired password length (min 4): ")
        if user_input.isdigit() and int(user_input) >= 4:
            length = int(user_input)
            break
        print("Please enter a valid number, 4 or greater.")

    password = generate_password(length)
    print(f"\nYour generated password: {password}")


if __name__ == "__main__":
    main()