# -*- coding: utf-8 -*-
"""Decodelabs-Task-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x89EoBPepOaKrVo-r-RurI_I1uHQxCx5

Um Ul Baneen
Artificial Intelligence Internship
"""



"""
Data Classification Using AI
Loads a dataset, splits it into train/test sets, trains a classifier,
and evaluates its performance.
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd


def load_data():
    """Load the Iris dataset and return it as a DataFrame + target."""
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df["target"] = iris.target
    print("Dataset shape:", df.shape)
    print("\nFirst 5 rows:\n", df.head())
    print("\nClass distribution:\n", df["target"].value_counts())
    return iris.data, iris.target, iris.target_names


def split_data(X, y):
    """Split data into training and testing sets (80/20)."""
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"\nTraining samples: {len(X_train)} | Testing samples: {len(X_test)}")
    return X_train, X_test, y_train, y_test


def train_model(X_train, y_train):
    """Train a simple K-Nearest Neighbors classifier."""
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(X_train, y_train)
    return model


def evaluate_model(model, X_test, y_test, target_names):
    """Evaluate the trained model on test data."""
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    print(f"\nAccuracy: {accuracy:.2%}")
    print("\nClassification Report:\n")
    print(classification_report(y_test, predictions, target_names=target_names))


def main():
    X, y, target_names = load_data()
    X_train, X_test, y_train, y_test = split_data(X, y)
    model = train_model(X_train, y_train)
    evaluate_model(model, X_test, y_test, target_names)


if __name__ == "__main__":
    main()