# -*- coding: utf-8 -*-
"""Decodelabs-Task-04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x89EoBPepOaKrVo-r-RurI_I1uHQxCx5

Um Ul Baneen
Artificial Intelligence Internship
"""

import os

# Install Tesseract OCR engine
if not os.path.exists('/usr/bin/tesseract'):
    print("Installing Tesseract OCR engine...")
    !sudo apt update > /dev/null
    !sudo apt install -y tesseract-ocr > /dev/null
    print("Tesseract OCR engine installed.")

# Install pytesseract Python wrapper
try:
    import pytesseract
except ImportError:
    print("Installing pytesseract Python wrapper...")
    !pip install -q pytesseract
    import pytesseract
    print("pytesseract installed.")


"""
Basic Text Recognition (OCR)
Generates a sample image containing text, then uses Tesseract OCR
(a pre-trained text recognition engine) to read the text back out.
"""

from PIL import Image, ImageDraw, ImageFont



def create_sample_image(text, filename="sample_text.png"):
    """Create a simple white image with black text, to act as sample input."""
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32)
    except IOError:
        font = ImageFont.load_default()

    # Size the image to fit the text, with padding
    dummy_img = Image.new("RGB", (1, 1))
    bbox = ImageDraw.Draw(dummy_img).textbbox((0, 0), text, font=font)
    width, height = bbox[2] - bbox[0] + 40, bbox[3] - bbox[1] + 40

    img = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(img)
    draw.text((20, 20), text, fill="black", font=font)
    img.save(filename)
    return filename


def recognize_text(image_path):
    """Run OCR on the given image and return the extracted text."""
    img = Image.open(image_path)
    extracted_text = pytesseract.image_to_string(img)
    return extracted_text.strip()


def main():
    original_text = "Hello Baneen, AI Internship 2026"

    print("Step 1: Creating sample image with text...")
    image_path = create_sample_image(original_text)
    print(f"Sample image saved as: {image_path}")

    print("\nStep 2: Running OCR (Tesseract) on the image...")
    recognized_text = recognize_text(image_path)

    print("\n--- RESULTS ---")
    print(f"Original text embedded in image : {original_text}")
    print(f"Text recognized by OCR model     : {recognized_text}")

    match = original_text.strip() == recognized_text.strip()
    print(f"Match: {'Yes, exact match' if match else 'Close match (OCR may have minor differences)'}")


if __name__ == "__main__":
    main()