# -*- coding: utf-8 -*-
"""Decodelabs-Task-01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x89EoBPepOaKrVo-r-RurI_I1uHQxCx5

Um Ul Baneen
Artificial Intelligence Internship
"""

"""
Rule-Based AI Chatbot
Handles greetings, small talk, and exit commands using if-else logic.
"""

def get_response(user_input):
    text = user_input.lower().strip()

    # Greetings
    if text in ["hi", "hello", "hey", "hola", "salam", "assalamualaikum"]:
        return "Hello! How can I help you today?"

    # How are you
    elif "how are you" in text:
        return "I'm just a bunch of if-else statements, but I'm doing great! How about you?"

    # Name
    elif "your name" in text:
        return "I'm ChatBuddy, your friendly rule-based chatbot."

    # Thanks
    elif text in ["thanks", "thank you", "shukriya"]:
        return "You're welcome!"

    # Help
    elif "help" in text:
        return "You can ask me things like 'hi', 'how are you', 'your name', or type 'bye' to exit."

    # Weather (fixed rule-based response, no real API)
    elif "weather" in text:
        return "I can't check live weather yet, but I hope it's sunny where you are!"

    # Exit commands
    elif text in ["bye", "exit", "quit", "goodbye"]:
        return "EXIT"

    # Default fallback
    else:
        return "Sorry, I didn't understand that. Type 'help' to see what I can do."


def chatbot():
    print("ChatBuddy: Hi! I'm a rule-based chatbot. Type 'bye' to exit.\n")

    while True:
        user_input = input("You: ")
        response = get_response(user_input)

        if response == "EXIT":
            print("ChatBuddy: Goodbye! Have a great day.")
            break

        print(f"ChatBuddy: {response}")


if __name__ == "__main__":
    chatbot()